# Generated by Django 4.1.7 on 2023-03-26 17:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('locality', models.TextField(verbose_name='Locality')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('state', models.TextField(verbose_name='City')),
                ('zipcode', models.IntegerField(verbose_name='zip code')),
                ('type', models.CharField(blank=True, choices=[('home', 'Home'), ('office', 'Office'), ('other', 'Other')], max_length=50, null=True, verbose_name='Address Type')),
                ('is_default', models.BooleanField(default=True, verbose_name='Is Default Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_address', to=settings.AUTH_USER_MODEL, verbose_name='User Address')),
            ],
            options={
                'verbose_name': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_wishlist', to='product.product', verbose_name='User Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_items', to=settings.AUTH_USER_MODEL, verbose_name='Wishlist')),
            ],
            options={
                'verbose_name': 'wishlist',
                'verbose_name_plural': 'wishlist',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Order Amount')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('order_id', models.CharField(max_length=10, unique=True, verbose_name='Order Id')),
                ('ordered_date', models.DateField(verbose_name='Order Date')),
                ('order_status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transition', 'In Transition'), ('delivered', 'Delivered')], max_length=40, verbose_name='Order Status')),
                ('is_return', models.BooleanField(default=False, verbose_name='Is Return')),
                ('return_reason', models.CharField(choices=[('bought_by_mistake', 'Bought By Mistake'), ('better_price_available', 'Better Price Available'), ('inadequate_quality', 'Inadequate Quality'), ('not_useful', 'Not Useful'), ('product_damaged', 'Product Damaged'), ('late_arrival', 'Late Arrival'), ('missing_accessories', 'Missing Accesories'), ('wrong_item_sent', 'Wrong Item Sent'), ('shipping_box_damaged', 'Shipping box Damaged'), ('inadequate_description', 'Inadequate Description')], max_length=200, verbose_name='Return Reason')),
                ('is_exchange', models.BooleanField(default=False, verbose_name='Is Exchange')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_address', to='order.address', verbose_name='User Address')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_coupon', to='payment.coupon', verbose_name='User Coupon')),
                ('product', models.ManyToManyField(related_name='product_order', to='product.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_orders', to=settings.AUTH_USER_MODEL, verbose_name='User Orders')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product_quantity', models.IntegerField(default=1, verbose_name='Product quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_cart', to='product.product', verbose_name='User Items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Cart')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'cart',
            },
        ),
    ]
