# Generated by Django 4.1.7 on 2023-04-10 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_address', to=settings.AUTH_USER_MODEL, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_cart_items', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_reason',
            field=models.CharField(choices=[('bought_by_mistake', 'Bought By Mistake'), ('better_price_available', 'Better Price Available'), ('inadequate_quality', 'Inadequate Quality'), ('not_useful', 'Not Useful'), ('product_damaged', 'Product Damaged'), ('late_arrival', 'Late Arrival'), ('missing_accessories', 'Missing Accesories'), ('wrong_item_sent', 'Wrong Item Sent'), ('shipping_box_damaged', 'Shipping box Damaged'), ('inadequate_description', 'Inadequate Description'), ('no_return', 'No Return')], max_length=200, verbose_name='Return Reason'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_items', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
