# Generated by Django 4.1.7 on 2023-03-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_group_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfabric',
            name='percentage',
            field=models.CharField(default='default_value', max_length=200, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sleeve_length',
            field=models.CharField(choices=[('long_sleeves', 'Long Sleeves'), ('short_sleeves', 'Short Sleeves'), ('three_quarter_sleeves', 'Three Quarter Sleeves'), ('sleeveless', 'Sleeveless'), ('not_applicable', 'Not Applicable')], max_length=25, verbose_name='Sleeve Length'),
        ),
    ]
