# Generated by Django 4.1.7 on 2023-03-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productfabric_percentage_alter_product_sleeve_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfabric',
            name='percentage',
            field=models.CharField(blank=True, default='default_value', max_length=200, null=True, verbose_name='Percentage'),
        ),
    ]
