# Generated by Django 4.1.7 on 2023-03-26 17:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Coupon Code')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coupon Usage Limit')),
                ('usage_type', models.CharField(choices=[('single_use', 'Single Use'), ('multi_use', 'Multi Use')], max_length=40, verbose_name='Number of usage')),
                ('coupon_type', models.CharField(choices=[('price', 'Price'), ('percentage', 'Percentage')], max_length=40, verbose_name='Coupon Type')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Payed')),
                ('date', models.DateField(blank=True, default=1, null=True, verbose_name='Payment Date')),
                ('mode', models.CharField(choices=[('upi', 'UPI'), ('credit_card', 'Credit Card'), ('paytm', 'Paytm'), ('net_banking', 'Net Banking'), ('emi', 'Emi'), ('cash_on_delivery', 'Cash on delivery')], max_length=40, verbose_name='Mode Of Payment')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_coupons', to='payment.coupon', verbose_name='Coupons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_payment', to=settings.AUTH_USER_MODEL, verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('refund_requested', models.BooleanField(default=False, verbose_name='Is Refund Requested')),
                ('refund_granted', models.BooleanField(default=False, verbose_name='Is refund accepted')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_refund', to='payment.payment', verbose_name='Refund')),
            ],
            options={
                'verbose_name': 'refund',
                'verbose_name_plural': 'refunds',
            },
        ),
    ]
