# Generated by Django 4.1.7 on 2023-04-10 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of usage'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_type',
            field=models.CharField(choices=[('single_use', 'Single Use'), ('multi_use', 'Multi Use')], max_length=40, verbose_name='Coupon Usage Limit'),
        ),
    ]
